# Generated by Django 4.2.2 on 2023-09-17 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_customuser_activeaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='photo_profile',
            field=models.ImageField(blank=True, default='photo_profile/defaut_profile.png', null=True, upload_to='photo_profile/', verbose_name='Фото профиля пользователя'),
        ),
    ]
