# Generated by Django 4.2.2 on 2023-09-18 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_photo_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='activeAccount',
        ),
    ]
