# Generated by Django 4.2.2 on 2023-09-24 16:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_customuser_photo_profile_questionnaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameProject', models.CharField(max_length=200, verbose_name='Назваение проекта')),
                ('waitSolary', models.CharField(max_length=200, verbose_name='Ожидаемая оплата')),
                ('description', models.CharField(max_length=300, verbose_name='Описание проекта')),
                ('list_skill', models.CharField(max_length=200, verbose_name='Перечень требуемых навыков')),
                ('list_task', models.CharField(max_length=200, verbose_name='Перечень требуемых задач')),
                ('posts', models.CharField(max_length=1000, verbose_name='Необходимые должности')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CustomUserr', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
    ]
