# Generated by Django 4.2.2 on 2023-09-24 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_project_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200, verbose_name='Краткая информация')),
                ('number_phone', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('state', models.CharField(default='Active', max_length=50, verbose_name='Состояние')),
                ('isAccept', models.BooleanField(default=True, verbose_name='Принял ли?')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='RecipientUser', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SenderUser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
    ]
